language: scala
scala:
  - "2.10.6"
  - "2.11.7"
jdk: oraclejdk7

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

script:
  - sbt clean coverage test coverageReport coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - neville@spotify.com
    - rav@spotify.com
